---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.1
    env:
     - "my_root_password=Apache75.$$." 
     #- "link_key="
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s https://raw.githubusercontent.com/VitalPointAI/Validator/main/start.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 3030
        as: 3030
        to:
          - global: true
      - port: 24567
        as: 24567
        to:
          - global: true
      - port: 3000
        as: 3000
        to:
          - global: true
profiles:
  compute:
    nearnode:
      resources:
        cpu:
          units: 12.0
        memory:
          size: 16Gi
        storage:
          size: 600Gi        
  placement:
    akash: 
      pricing:
        nearnode:
          denom: uakt
          amount: 10000
deployment:
  nearnode:
    akash:
      profile: nearnode
      count: 1 